- name: play level variables
  hosts: local
  connection: local
  vars:   # global access
    COURSE: Devops with AWS
    DURATION: 10hrs
    NAME: Anand
  tasks:
  - name: print course information
    vars:  # local access
      COURSE: Ansible
    ansible.builtin.debug:
      msg: "hello {{ COURSE }}, Course Duration: {{ DURATION }}, my name {{ NAME }}"

  - name: print course information again
    ansible.builtin.debug:
      msg: "hello {{ COURSE }}, Course Duration: {{ DURATION }}, my name {{ NAME }}"