- name: play level variables
  hosts: local
  connection: local
  vars_files:
  tasks:
  - name: print course information
    ansible.builtin.debug:
      msg: "hello {{ COURSE }}, Course Duration: {{ DURATION }}, my name {{ NAME }}"